name: Deploy on Save

on:
  push:
    paths:
      - '/CIRCUITPY/**'

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to CIRCUITPY drive
        run: |
          cp -r /CIRCUITPY/* /Volumes/CIRCUITPY
